# .github/workflows/python-ci.yml

name: Python CI

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8  # Install flake8 for linting

    - name: Lint with flake8
      run: |
        flake8 instareel_downloader.py  # Run flake8 on your main script
      continue-on-error: true  # Continue even if linting fails (optional)

    - name: Run tests (Optional)
      run: |
        # If you have tests, you can run them here.
        # For example, if you have pytest installed:
        # pytest
        echo "No tests to run."
